name: Trigger API Build

on:
  push:
    branches:
      - development

jobs:
  trigger-build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: peaceful-garden-425612-d8  # Replace with your actual project ID
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Publish message to Pub/Sub
        run: |
          gcloud pubsub topics publish frontend-development-changes \
            --message="{\"repository\":\"ChargeCaptureWebAppV2\",\"branch\":\"development\",\"commit\":\"${{ github.sha }}\"}" \
            --attribute="event=push,repository=ChargeCaptureWebAppV2,branch=development"
